version: 1.x.{build}

shallow_clone: true

platform:
  - x86
  - x64

#matrix:
#  fast_finish: true

clone_folder: c:\projects\IsoCodesValidator

init:
  - SET PATH=c:\tools\php;%PATH%
  - SET PHP=1

install:
  - cinst php
  - cd c:\tools\php
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - echo @php "%~dp0composer.phar" %* > composer.bat
  - cd c:\projects\IsoCodesValidator
  - composer global update --prefer-dist --no-interaction
  - composer update --prefer-dist --no-interaction

test_script: make test
